site_name: PSGraph Docs
repo_url: https://github.com/KevinMarquette/PSGraph
theme: readthedocs
pages:
  - Home: index.md
  - PSGraph Basics:
    - What is PSGraph: about.md
    - Quick Start: Quick-Start-Installation-and-Example.md
  - Commands:
    - Graph: Command-Graph.md
    - Edge: Command-Edge.md
    - Node: Command-Node.md
    - Inline: Command-Inline.md
    - SubGraph: Command-SubGraph.md
    - Record: Command-Record.md
    - Row: Command-Row.md
    - Entity: Command-Entity.md
    - Export-PSGraph: Command-Export-PSGraph.md
    - Show-PSGraph: Command-Show-PSGraph.md
  - Advanced:
    - GraphViz Documentation: graphviz.md
  - Examples:
    - Gallery: Example-Gallery.md
    - Scripted: Example-Scripted.md
    - State Machine: Example-State-Machine.md
  - Acknowledgements: acknowledgements.md